import Head from 'next/head';
import Image from 'next/image';
import profileImage from '../public/profileImage.jpg';
import reaectToDoAppImage from '../public/reactToDoAppImage.png'
import minimalisticLandingPageImage from '../public/minimalisticLandingPage.png'
import check24ProfisLogo from '../public/check24ProfisLogo.png'
import printManiaLogo from '../public/print_mania.png'
import instaBotLogo from '../public/instabot.jpeg'
import googleLogo from '../public/googleLogo.png'
import btuLogoImage from '../public/btuLogo.png'
import ibmIxLogo from '../public/ibmIx.png'
import auto1Logo from '../public/auto1GroupLogo.jpeg'
import bvLogo from '../public/bvLogo.jpeg'
import csufLogo from '../public/csufLogo.png'
import rmitLogo from '../public/rmitLogo.png'
import courseraLogo from '../public/courseraLogo.jpeg'
import {MdVerified} from 'react-icons/md';
import {AiFillPlayCircle} from 'react-icons/ai';
import {BsThreeDots, BsFillPlayFill} from 'react-icons/bs'
import {IoIosArrowBack} from 'react-icons/io'
import Link from 'next/link';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Certifications & Recommendations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotifyIcon.ico" />
      </Head>
      <main className='text-white font-gothamBold bg-black h-screen '>
        <nav className='flex bg-slate-800 justify-start items-center h-14'>
            <div className=' w-2/12 md:w-1/12 lg:w-1/12 text-white'>
                <Link href='./'>
                    <IoIosArrowBack className='w-8 h-14 ml-4'/>
                </Link>
            </div>
            <div className='w-screen text-center'>
                <h3>Certifications & Recommendations</h3>
            </div>
        </nav>
            {/*SECTION: Certificates*/}
            <div className='w-screen'>
                <div id='certificationsHistorySection' className='bg-black'>
                    <h2 className="text-3xls p-4 text-white">Certifications</h2>
                    <div id="myPortfolioItems" className=' font-gothamBold text-xs'>
                        <div id="PortfolioItemGroup" class="group">
                            <div id='PortfolioItem' className=' group-hover:bg-gray-700 rounded-md max-w-xl relative mx-4'>
                            <a href='https://www.coursera.org/account/accomplishments/specialization/certificate/RDCB66AKZR6E' target="_blank" rel="noreferrer" className='absolute top-0 bottom-0 left-0 right-0'>
                            </a>
                                <div id='containerAllItems' className='flex items-center justify-between gap-6 '>
                                    <div id='containerImageTitle' className='flex items-center py-2  gap-6'>
                                        <div className='relative pointer-events-none z-0 w-16 h-16 ml-2'>
                                            <a href='https://www.coursera.org/account/accomplishments/professional-cert/RDCB66AKZR6E' target="_blank" rel="noreferrer" className='pointer-events-auto'>
                                            <Image src={googleLogo} alt="fallback-text" layout='fill' objectfit='cover'/>
                                            </a>
                                        </div>
                                        
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>
                                            Google IT Automation with Python
                                            </h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>
                                            Google
                                            </p>
                                        </div>
                                    </div>
                                    <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>
                                    Issued October 2021
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div id="PortfolioItemGroup" class="group">
                            <div id='PortfolioItem' className=' group-hover:bg-gray-700 rounded-md max-w-xl relative mx-4'>
                            <a href='https://www.coursera.org/account/accomplishments/certificate/4AXBCMRR3HXH' target="_blank" rel="noreferrer" className='absolute top-0 bottom-0 left-0 right-0'>
                            </a>
                                <div id='containerAllItems' className='flex items-center justify-between gap-6 '>
                                    <div id='containerImageTitle' className='flex items-center py-2  gap-6'>
                                        <div className='relative pointer-events-none z-0 w-16 h-16 ml-2'>
                                            <a href='https://www.coursera.org/learn/bootstrap-4' target="_blank" rel="noreferrer" className='pointer-events-auto'>
                                            <Image src={courseraLogo} alt="fallback-text" layout='fill' objectfit='cover'/>
                                            </a>
                                        </div>
                                        
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>
                                            Front-End Web UI Frameworks and Tools: Bootstrap 4
                                            </h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>
                                            Coursera
                                            </p>
                                        </div>
                                    </div>
                                    <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>
                                    Issued August 2021
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div id="PortfolioItemGroup" class="group">
                            <div id='PortfolioItem' className=' group-hover:bg-gray-700 rounded-md max-w-xl relative mx-4'>
                            <a href='https://www.coursera.org/account/accomplishments/certificate/Q7JSQHAYXBLD' target="_blank" rel="noreferrer" className='absolute top-0 bottom-0 left-0 right-0'>
                            </a>
                                <div id='containerAllItems' className='flex items-center justify-between gap-6 '>
                                    <div id='containerImageTitle' className='flex items-center py-2  gap-6'>
                                        <div className='relative pointer-events-none z-0 w-16 h-16 ml-2'>
                                            <a href='https://www.coursera.org/account/accomplishments/verify/Q7JSQHAYXBLD' target="_blank" rel="noreferrer" className='pointer-events-auto'>
                                            <Image src={googleLogo} alt="fallback-text" layout='fill' objectfit='cover'/>
                                            </a>
                                        </div>
                                        
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>
                                            Crash Course on Python
                                            </h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>
                                            Google
                                            </p>
                                        </div>
                                    </div>
                                    <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>
                                    Issued May 2021
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div id="PortfolioItemGroup" class="group">
                            <div id='PortfolioItem' className=' group-hover:bg-gray-700 rounded-md max-w-xl relative mx-4'>
                            <a href='https://www.coursera.org/account/accomplishments/certificate/B86VSHH48CUE' target="_blank" rel="noreferrer" className='absolute top-0 bottom-0 left-0 right-0'>
                            </a>
                                <div id='containerAllItems' className='flex items-center justify-between gap-6 '>
                                    <div id='containerImageTitle' className='flex items-center py-2  gap-6'>
                                        <div className='relative pointer-events-none z-0 w-16 h-16 ml-2'>
                                            <a href='https://www.coursera.org/account/accomplishments/verify/B86VSHH48CUE' target="_blank" rel="noreferrer" className='pointer-events-auto'>
                                            <Image src={googleLogo} alt="fallback-text" layout='fill' objectfit='cover'/>
                                            </a>
                                        </div>
                                        
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>
                                            Using Python to Interact with the Operating System

                                            </h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>
                                            Google
                                            </p>
                                        </div>
                                    </div>
                                    <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>
                                    Issued June 2021
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div id="PortfolioItemGroup" class="group">
                            <div id='PortfolioItem' className=' group-hover:bg-gray-700 rounded-md max-w-xl relative mx-4'>
                            <a href='https://www.coursera.org/account/accomplishments/certificate/Y73BAXWKKXHW' target="_blank" rel="noreferrer" className='absolute top-0 bottom-0 left-0 right-0'>
                            </a>
                                <div id='containerAllItems' className='flex items-center justify-between gap-6 '>
                                    <div id='containerImageTitle' className='flex items-center py-2  gap-6'>
                                        <div className='relative pointer-events-none z-0 w-16 h-16 ml-2'>
                                            <a href='https://www.coursera.org/account/accomplishments/verify/Y73BAXWKKXHW' target="_blank" rel="noreferrer" className='pointer-events-auto'>
                                            <Image src={googleLogo} alt="fallback-text" layout='fill' objectfit='cover'/>
                                            </a>
                                        </div>
                                        
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>
                                            Introduction to Git and GitHub

                                            </h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>
                                            Google
                                            </p>
                                        </div>
                                    </div>
                                    <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>
                                    Issued August 2021
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div id="PortfolioItemGroup" class="group">
                            <div id='PortfolioItem' className=' group-hover:bg-gray-700 rounded-md max-w-xl relative mx-4'>
                            <a href='https://www.coursera.org/account/accomplishments/certificate/KD826V2FYTTT' target="_blank" rel="noreferrer" className='absolute top-0 bottom-0 left-0 right-0'>
                            </a>
                                <div id='containerAllItems' className='flex items-center justify-between gap-6 '>
                                    <div id='containerImageTitle' className='flex items-center py-2  gap-6'>
                                        <div className='relative pointer-events-none z-0 w-16 h-16 ml-2'>
                                            <a href='https://www.coursera.org/account/accomplishments/verify/KD826V2FYTTT' target="_blank" rel="noreferrer" className='pointer-events-auto'>
                                            <Image src={googleLogo} alt="fallback-text" layout='fill' objectfit='cover'/>
                                            </a>
                                        </div>
                                        
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>
                                            Troubleshooting and Debugging Techniques

                                            </h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>
                                            Google
                                            </p>
                                        </div>
                                    </div>
                                    <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>
                                    Issued September 2021
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div id="PortfolioItemGroup" class="group">
                            <div id='PortfolioItem' className=' group-hover:bg-gray-700 rounded-md max-w-xl relative mx-4'>
                            <a href='https://www.coursera.org/account/accomplishments/certificate/8E2587W6GASA' target="_blank" rel="noreferrer" className='absolute top-0 bottom-0 left-0 right-0'>
                            </a>
                                <div id='containerAllItems' className='flex items-center justify-between gap-6 '>
                                    <div id='containerImageTitle' className='flex items-center py-2  gap-6'>
                                        <div className='relative pointer-events-none z-0 w-16 h-16 ml-2'>
                                            <a href='https://www.coursera.org/account/accomplishments/verify/8E2587W6GASA' target="_blank" rel="noreferrer" className='pointer-events-auto'>
                                            <Image src={googleLogo} alt="fallback-text" layout='fill' objectfit='cover'/>
                                            </a>
                                        </div>
                                        
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>
                                            Configuration Management and the Cloud

                                            </h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>
                                            Google
                                            </p>
                                        </div>
                                    </div>
                                    <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>
                                    Issued October 2021
                                    </p>
                                </div>
                            </div>
                        </div>

                        <div id="PortfolioItemGroup" class="group">
                            <div id='PortfolioItem' className=' group-hover:bg-gray-700 rounded-md max-w-xl relative mx-4'>
                            <a href='https://www.coursera.org/account/accomplishments/certificate/P74P725PVAWL' target="_blank" rel="noreferrer" className='absolute top-0 bottom-0 left-0 right-0'>
                            </a>
                                <div id='containerAllItems' className='flex items-center justify-between gap-6 '>
                                    <div id='containerImageTitle' className='flex items-center py-2  gap-6'>
                                        <div className='relative pointer-events-none z-0 w-16 h-16 ml-2'>
                                            <a href='https://www.coursera.org/account/accomplishments/verify/P74P725PVAWL' target="_blank" rel="noreferrer" className='pointer-events-auto'>
                                            <Image src={googleLogo} alt="fallback-text" layout='fill' objectfit='cover'/>
                                            </a>
                                        </div>
                                        
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>
                                            Automating Real-World Tasks with Python

                                            </h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>
                                            Google
                                            </p>
                                        </div>
                                    </div>
                                    <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>
                                    Issued October 2021
                                    </p>
                                </div>
                            </div>
                        </div>


                    </div>


                    <h2 className="text-3xls p-4 pt-4 text-white">Recommendations</h2>
                    <div id="myPortfolioItems" className=' font-gothamBold text-xs'>
                        <div id="PortfolioItemGroup" class="group">
                            <Link href='https://www.rmit.edu.vn/' target="_blank" rel="noreferrer">
                                <div id='PortfolioItem' className='py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl'>
                                    <div id='containerAllItems' className='flex items-center justify-between gap-6'>
                                        <div id='containerImageTitle' className='flex items-center gap-6'>
                                        <div className='ml-2 w-16 h-16'>
                                        <Image src={rmitLogo} alt="fallback-text" layout='fill' objectFit='cover'/>
                                        </div>
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>RMIT University</h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>Vietnam</p>
                                        </div>
                                        </div>
                                        <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>October 2016 - January 2017</p>
                                    </div>
                                </div>
                            </Link>
                        </div>
                    </div>

                    <div id="myPortfolioItems" className=' font-gothamBold text-xs'>
                        <div id="PortfolioItemGroup" class="group">
                            <Link href='http://www.fullerton.edu/' target="_blank" rel="noreferrer">
                                <div id='PortfolioItem' className='py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl'>
                                    <div id='containerAllItems' className='flex items-center justify-between gap-6'>
                                        <div id='containerImageTitle' className='flex items-center gap-6'>
                                        <div className='ml-2 w-16 h-16'>
                                        <Image src={csufLogo} alt="fallback-text" layout='fill' objectFit='cover'/>
                                        </div>
                                        <div className='text-white w-18'>
                                            <h4 className='w-44 sm:w-64 md:w-64 xl:w-72 text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base'>California State University (CSUF)</h4>
                                            <p className='group-hover:text-white text-left font-gothamLight'>Fullerton</p>
                                        </div>
                                        </div>
                                        <p className='text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2'>August 2013 - December 2013</p>
                                    </div>
                                </div>
                            </Link>
                        </div>
                    </div>
                </div>
            </div>
      </main>
    </div>
  )
}


