import Head from "next/head";
import Image from "next/image";
import profileImage from "../public/profileImage.jpg";
import reaectToDoAppImage from "../public/reactToDoAppImage.png";
import minimalisticLandingPageImage from "../public/minimalisticLandingPage.png";
import check24ProfisLogo from "../public/check24ProfisLogo.png";
import printManiaLogo from "../public/print_mania.png";
import instaBotLogo from "../public/instabot.jpeg";
import btuLogoImage from "../public/btuLogo.png";
import ibmIxLogo from "../public/ibmIx.png";
import auto1Logo from "../public/auto1GroupLogo.jpeg";
import bvLogo from "../public/bvLogo.jpeg";
import { MdVerified } from "react-icons/md";
import { AiFillPlayCircle } from "react-icons/ai";
import { BsThreeDots, BsFillPlayFill } from "react-icons/bs";
import { IoIosArrowBack } from "react-icons/io";
import Link from "next/link";
import Navbar from "../components/Navbar";
import BigListItem from "../components/BigListItem";

let seniorProjectPage = "/seniorProjects";
let professionalProjectPage = "/professionalProjects";
let printManiaInstagram = "https://www.instagram.com/sneaker_mania_berlin/";
let juniorProjectPage = "/juniorProjects";
let bvbPage = "https://www.berliner-volksbank.de/homepage.html";
let ibmiXPage = "https://ibmix.de/en/";
let btuPage = "https://www.b-tu.de/";
let auto1GroupPage = "https://www.auto1-group.com/";
let googleItAutomationWithPython =
  "https://www.coursera.org/account/accomplishments/specialization/certificate/RDCB66AKZR6E";
let crashCourseOnPython =
  "https://www.coursera.org/account/accomplishments/certificate/4AXBCMRR3HXH";

export default function Home() {
  let pageName = "Employment History";
  return (
    <div>
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotifyIcon.ico" />
      </Head>
      <main className="text-white font-gothamBold h-screen md:px-24 lg:px-48 3xl:px-128 bg-black  ">
        <Navbar headerName={pageName} />
        {/*SECTION: Employment History*/}
        <div className="w-screen pt-14">
          <div id="employmentHistorySection" className="bg-black">
            <h2 className="text-3xls p-4 text-white">Full Time</h2>
            <div id="myPortfolioItems" className=" font-gothamBold text-xs">
              <BigListItem
                src={check24ProfisLogo}
                title="Senior Product Manager"
                subline="CHECK24 Profis"
                durationText="January 2022 - Present"
                href={seniorProjectPage}
              />

              <BigListItem
                src={check24ProfisLogo}
                title="Professional Product Manager"
                subline="CHECK24 Profis"
                durationText="April 2019 - December 2021"
                href={professionalProjectPage}
              />

              <BigListItem
                src={check24ProfisLogo}
                title="Junior Product Manager"
                subline="CHECK24 Profis"
                durationText="April 2018 - March 2019"
                href={juniorProjectPage}
              />

              <BigListItem
                src={bvLogo}
                title="Account Manager"
                subline="Berliner Volksbank"
                durationText="July 2011 - September 2011"
                href={bvbPage}
              />
            </div>

            <h2 className="text-3xls p-4 pt-4 text-white">Working Student</h2>
            <div id="myPortfolioItems" className=" font-gothamBold text-xs">
              <BigListItem
                src={ibmIxLogo}
                title="Project Manager"
                subline="IBM iX"
                durationText="March 2017 - March 2018"
                href={ibmiXPage}
              />

              <BigListItem
                src={auto1Logo}
                title="Business Development Manager"
                subline="AUTO1 Group"
                durationText="October 2015 - October 2016"
                href={auto1GroupPage}
              />
            </div>

            <h2 className="text-3xls p-4 pt-4 text-white">Apprenticeship</h2>
            <div
              id="myPortfolioItems"
              className=" font-gothamBold text-xs pb-20"
            >
              <BigListItem
                src={bvLogo}
                title="Account Manager"
                subline="Bank Clerk"
                durationText="August 2009 - June 2011"
                href={bvbPage}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
