import Head from 'next/head';
import Image from 'next/image';

import profileImage from '../public/profileImage.jpg';
import reaectToDoAppImage from '../public/reactToDoAppImage.png'
import minimalisticLandingPageImage from '../public/minimalisticLandingPage.png'
import loginPage from '../public/toDoApp/loginPage.png'
import loginPageMobile from '../public/toDoApp/loginHTML.png'
import check24ProfisLogo from '../public/check24ProfisLogo.png'
import printManiaLogo from '../public/print_mania.png'
import instaBotLogo from '../public/instabot.jpeg'
import btuLogoImage from '../public/btuLogo.png'
import {MdVerified} from 'react-icons/md';
import {AiFillPlayCircle} from 'react-icons/ai';
import {BsThreeDots, BsFillPlayFill, BsGithub} from 'react-icons/bs'
import {IoIosArrowBack} from 'react-icons/io'
import Link from 'next/link';
import Navbar from '../components/Navbar';


export default function Home() {
    let pageName ='Instagram LikeBot'
    return (
    <div >
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotifyIcon.ico" />
      </Head>
      <main className='text-white font-gothamBold bg-black h-screen break-words md:px-24 lg:px-40 2xl:px-48' >
        <Navbar headerName={pageName}/>
        <div className=' bg-black pt-16 px-4 grid grid-cols-1 lg:grid-cols-8 gap-4'>
            <div id='leftContainer' className='lg:col-span-4 lg:py-4 bg-black'>
                <div id='headerContainer' className=' lg:hidden'>
                    <h1 className=' font-gothamLight text-sm'>Personal Project</h1>
                    <h2 className=' text-2xl '>My Instagram Bot</h2>
                </div>

                <div id='imageContainer' className='pt-2 lg:pt-12 h-1/3 w-auto rounded'>                
                    <div className='relative'>
                        <Image src={loginPage} alt="fallback-text" className='overflow-hidden rounded lg:hidden'/> 
                        <Image src={loginPageMobile} alt="fallback-text" className='hidden lg:inline-block overflow-hidden rounded'/> 
                        <a href='https://github.com/fabianszyman/myinstagram-bot' target="_blank" rel="noreferrer">
                            <button className=' absolute top-4 right-4 text-black bg-white rounded-full px-7 py-3 hover:scale-105 border border-gray-400 hover:border-green-500  m-2 '>
                                <div className='flex items-center gap-2'>
                                    <BsGithub/> 
                                        Github
                                </div>
                            </button>
                        </a>
                    </div>
                </div>
            </div>    

                <div id='rightContainer' className='lg:col-span-4 bg-black'>
                    <div id='headerContainer' className='hidden lg:inline-block pb-3'>
                        <h1 className=' font-gothamLight text-sm'>Personal Project</h1>
                        <h2 className=' text-2xl '>My Instagram Bot</h2>
                    </div>
                    <div id='textContainer'>
                        <div className='text-lg'>
                        Background:
                        </div>
                        <div className='font-gothamLight text-lg pt-1'>
                            <p className='pb-2'>
                                Während meiner Zeit bei CHECK24 Profis kam ich zum ersten mal mit dem Thema Web-Crawler und WebScraping in Kontakt. Als ich mich näher mit dem Thema auseinandergesetzt habe, merkte ich wie vielseitig die Möglichkeiten mittlerweile sind sowohl Klick-Flows als auch das Daten sammeln externer Seiten zu automatisieren.
                            </p>
                            
                            <p>
                                Da mit das Thema Automatisierung so sehr faszinierte, suchte ich mir ein konkretes Projekt, um unterschiedliche Ansätze besser zu verstehen. 
                            </p>
                            
                        </div>
                        <div className='text-lg pt-6'>
                        Idee:
                        </div>
                        <div className='font-gothamLight text-lg pt-1'>
                            <p>
                            Als Instagram Nutzer soll es mir möglich sein, bestimmte Such-Parameter einzugeben und damit ein Script zu starten, dass auf Grundlage meiner eingegebenen Input-Parametern automatisiert die neusten Instagram Post zu bestimmten Hashtags liked. 
                            </p>
                            
                            
                            
                            
                                
                        </div>
                        <div className='text-lg pt-6'>
                        Process:
                        </div>
                        <div className='font-gothamLight text-lg pt-1'>
                            <ul>
                                <li>
                                    1. Bau einer HTML Seite, um Input Parameter entgegen zu nehmen.
                                </li>
                                <li>
                                    2. Erstellen eine <a href='https://www.mongodb.com/' className='hover:underline hover:text-green-500'>MongoDB</a> Datenbank (Backend aufsetzen).
                                </li>
                                <li>
                                    3. Definition und bau mehrerer API Endpunkte mit Hilfe von <a href='https://expressjs.com/' className='hover:underline hover:text-green-500'>Express.js</a>.
                                </li>
                                <li>
                                    4. Bau der Automatisierungs-Logiken mit Hilfe von <a href='https://playwright.dev/' className='hover:underline hover:text-green-500'>Playwright.js</a>.  
                                </li>
                            </ul>
                                
                        </div>
                        <div className='text-lg pt-6'>
                        Github-Link:
                        </div>
                        <div className='font-gothamLight text-lg pt-1 pb-20'>
                            <a href='https://github.com/fabianszyman/myinstagram-bot' className='hover:underline hover:text-green-500'>
                                https://github.com/fabianszyman/myinstagram-bot
                            </a>
                                
                        </div>  
                    </div>
                </div>

            
        </div>



      </main>
    </div>
  )
}


