import Head from "next/head";
import Image from "next/image";
import profileImage from "../public/profileImage.jpg";
import reaectToDoAppImage from "../public/reactToDoAppImage.png";
import minimalisticLandingPageImage from "../public/minimalisticLandingPage.png";
import loginPage from "../public/toDoApp/loginPage.png";
import loginPageMobile from "../public/toDoApp/loginHTML.png";
import check24ProfisLogo from "../public/check24ProfisLogo.png";
import printManiaLogo from "../public/print_mania.png";
import instaBotLogo from "../public/instabot.jpeg";
import btuLogoImage from "../public/btuLogo.png";
import { MdVerified } from "react-icons/md";
import { AiFillPlayCircle } from "react-icons/ai";
import { BsThreeDots, BsFillPlayFill, BsGithub } from "react-icons/bs";
import { IoIosArrowBack } from "react-icons/io";
import Link from "next/link";
import Navbar from "../components/Navbar";
let check24ProfisURL = "https://www.check24.de/profis/";
let playwirghtjsURL = "https://playwright.dev/";
let instagramBusinessAccountURL =
  "https://www.instagram.com/sneaker_mania_berlin/";

let instagramLikeBotGitHubLink =
  "https://github.com/fabianszyman/myinstagram-bot";

let mongoDBURL = "https://www.mongodb.com/";

let expressjsURL = "https://expressjs.com/";

export default function Home() {
  let pageName = "Instagram LikeBot";
  return (
    <div>
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotifyIcon.ico" />
      </Head>
      <main className="text-white font-gothamBold bg-black h-full break-words md:px-24 lg:px-40 2xl:px-48 ">
        <Navbar headerName={pageName} />
        <div className=" bg-black px-4 grid grid-cols-1 lg:grid-cols-8 gap-6 py-20">
          <div id="leftContainer" className="lg:col-span-4 bg-black">
            <div id="headerContainer" className=" lg:hidden">
              <h1 className=" font-gothamLight text-sm">Personal Project</h1>
              <h2 className=" text-2xl ">{pageName}</h2>
            </div>

            <div
              id="imageContainer"
              className="pt-2 lg:pt-12 w-auto rounded lg:hidden overflow-hidden"
            >
              <div className="relative">
                <Image
                  src={loginPage}
                  alt="fallback-text"
                  className="rounded"
                />
                <a
                  href={instagramLikeBotGitHubLink}
                  target="_blank"
                  rel="noreferrer"
                >
                  <button className=" absolute top-4 right-4 text-black bg-white rounded-full px-7 py-3 hover:scale-105 border border-gray-400 hover:border-green-500  m-2 ">
                    <div className="flex items-center gap-2">
                      <BsGithub />
                      Github
                    </div>
                  </button>
                </a>
              </div>
            </div>

            <div id="headerContainer" className="hidden lg:inline-block pb-3">
              <h1 className=" font-gothamLight text-sm">Personal Project</h1>
              <h2 className=" text-2xl ">{pageName}</h2>
            </div>
            <div id="textContainer" className="pt-4">
              <h3 className="pt-0">Executive summary:</h3>
              <div className="font-gothamLight text-lg pt-1">
                <p className="pb-2">
                  Scaled my business Instagram account to more than 8.8k
                  follower by creating a script, that does human-like
                  interactions (e.g. liking, commenting and following).
                </p>
              </div>
              <h3>Background:</h3>
              <div className="font-gothamLight text-lg pt-1">
                <p>
                  In my time at{" "}
                  <a
                    href={check24ProfisURL}
                    className="underline hover:underline hover:text-green-500"
                  >
                    CHECK24 Profis
                  </a>{" "}
                  I first got in touch with the Node.js library{" "}
                  <a
                    href={playwirghtjsURL}
                    className="underline hover:underline hover:text-green-500"
                  >
                    Playwright.js
                  </a>
                  . After realizing how easy it is to automate click funnels, I
                  wanted to use this power of automation and mock human like
                  interaction for my{" "}
                  <a
                    href={instagramBusinessAccountURL}
                    className="underline hover:underline hover:text-green-500"
                  >
                    Instagram business account
                  </a>
                  .
                </p>
              </div>
              <h3>Idea:</h3>
              <div className="font-gothamLight text-lg pt-1">
                <p className="pb-2">
                  As a user, I should be able to define an array of prompts,
                  that will be typed in inside the search input. After clicking
                  on search, the script should select the latest entry and
                  either like it, write a comment or follow the user if the user
                  is not already followed.
                </p>
              </div>
              <h3>Process:</h3>

              <div className="font-gothamLight text-lg">
                <ul>
                  <li>1. Create HTML Frontend Input area.</li>
                  <li>
                    2. Build{" "}
                    <a
                      href={mongoDBURL}
                      className="underline hover:underline hover:text-green-500"
                    >
                      MongoDB
                    </a>{" "}
                    database.
                  </li>
                  <li>
                    3. Define API endpoints with{" "}
                    <a
                      href={expressjsURL}
                      className="underline hover:underline hover:text-green-500"
                    >
                      Express.js
                    </a>
                    .
                  </li>
                  <li>
                    4. Create functions using{" "}
                    <a
                      href={playwirghtjsURL}
                      className="underline hover:underline hover:text-green-500"
                    >
                      Playwright.js
                    </a>
                    .
                  </li>
                  <li>5. Connect all parts together.</li>
                </ul>
              </div>
              <h3 className="pt-6">Github-Link:</h3>
              <div className="font-gothamLight text-lg pt-1 pb-20">
                <a
                  href={instagramLikeBotGitHubLink}
                  className="underline hover:underline hover:text-green-500"
                >
                  https://github.com/fabianszyman/myinstagram-bot
                </a>
              </div>
            </div>
          </div>

          <div
            id="rightContainer"
            className="lg:col-span-4 lg:py-4 bg-black hidden lg:inline-block"
          >
            <div
              id="imageContainer"
              className="pt-2 lg:pt-12 h-1/3 w-auto rounded "
            >
              <div className="relative">
                <Image
                  src={loginPageMobile}
                  alt="fallback-text"
                  className="overflow-hidden rounded"
                />
                <a
                  href={instagramLikeBotGitHubLink}
                  target="_blank"
                  rel="noreferrer"
                >
                  <button className=" absolute top-4 right-4 text-black bg-white rounded-full px-7 py-3 hover:scale-105 border border-gray-400 hover:border-green-500  m-2 ">
                    <div className="flex items-center gap-2">
                      <BsGithub />
                      Github
                    </div>
                  </button>
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
