import Head from 'next/head';
import Image from 'next/image';
import profileImage from '../public/profileImage.jpg';
import reaectToDoAppImage from '../public/reactToDoAppImage.png'
import minimalisticLandingPageImage from '../public/minimalisticLandingPage.png'
import check24ProfisLogo from '../public/check24ProfisLogo.png'
import printManiaLogo from '../public/print_mania.png'
import instaBotLogo from '../public/instabot.jpeg'
import btuLogoImage from '../public/btuLogo.png'
import {MdVerified} from 'react-icons/md';
import {AiFillPlayCircle} from 'react-icons/ai';
import {BsThreeDots, BsFillPlayFill} from 'react-icons/bs'
import {IoIosArrowBack} from 'react-icons/io'
import Link from 'next/link';


export default function Home() {
  return (
    <div >
      <Head>
        <title>Portfolio Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotifyIcon.ico" />
      </Head>
      <main className='text-white font-gothamBold bg-black h-screen '>
        <nav className=' bg-slate-700 flex justify-start items-center relative h-14'>
            <div className='w-2/12 md:w-1/12 lg:w-1/12 flex items-center justify-center text-white'>
                <Link href='./portfolio'>
                    <IoIosArrowBack className='w-8 h-8'/>
                </Link>
            </div>
            <div className='w-screen flex items-center justify-center px-12'>
                <h3>Minimalistic Landing Page</h3>
            </div>
        </nav>
        <div className=' bg-black pt-4 px-4'>
            <h4 className=' font-gothamLight text-sm'>Personal Project</h4>
            <h1 className=' text-xl '>Responsive Single Page Landing Page</h1>
            <div className='pt-2 h-1/3 md:w-2/3 lg:w-2/3 hover:scale-105'>
                <Image src={minimalisticLandingPageImage} alt="fallback-text" className='overflow-hidden'/>
            </div>
            <div className='text-xl pt-6'>
            Overview

            </div>
            <div className='font-gothamLight text-lg pt-1'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
                molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
                numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
                optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis
                obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam
                nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit,
                tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit,
                quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos 
                sapiente officiis modi at sunt excepturi. 
            </div>
            <div className='text-xl pt-6'>
            Goal

            </div>
            <div className='font-gothamLight text-lg pt-1'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
                molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
                numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
                optio, eaque rerum! Provident similique accusantium nemo autem. 
         
            </div>
            <div className='text-xl pt-6'>
            Results

            </div>
            <div className='font-gothamLight text-lg pt-1'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
                molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
                numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
                optio, eaque rerum! Provident similique accusantium nemo autem. 
         
            </div>
            <div className='text-xl pt-6'>
            Process

            </div>
            <div className='font-gothamLight text-lg pt-1'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
                molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
                numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
                optio, eaque rerum! Provident similique accusantium nemo autem. 
         
            </div>
            <div className='text-xl pt-6'>
            Responsibilities

            </div>
            <div className='font-gothamLight text-lg pt-1'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,
                molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum
                numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium
                optio, eaque rerum! Provident similique accusantium nemo autem. 
         
            </div>
            <div className='text-xl pt-6'>
            Team

            </div>
            <ul className='font-gothamLight text-lg pt-1'>
                <li>1. Backend</li>
                <li>2. Frontend</li>
                <li>1. UX-Designer</li>
                <li>1. Product Manager</li>
         
            </ul>
        </div>



      </main>
    </div>
  )
}


