import Head from "next/head";
import Image from "next/image";

import profileImage from "../public/profileImage.jpg";
import reaectToDoAppImage from "../public/reactToDoAppImage.png";
import minimalisticLandingPageImage from "../public/minimalisticLandingPage.png";
import minimalisticLPBigImage from "../public/minimalisticLP_bigImage.png";
import minimalisticLPSmallImage from "../public/minimalisticLP_smallImage.png";
import loginPage from "../public/toDoApp/loginPage.png";
import loginPageMobile from "../public/toDoApp/loginHTML.png";
import check24ProfisLogo from "../public/check24ProfisLogo.png";
import printManiaLogo from "../public/print_mania.png";
import instaBotLogo from "../public/instabot.jpeg";
import btuLogoImage from "../public/btuLogo.png";
import { MdVerified } from "react-icons/md";
import { AiFillPlayCircle } from "react-icons/ai";
import { BsThreeDots, BsFillPlayFill, BsGithub } from "react-icons/bs";
import { IoIosArrowBack } from "react-icons/io";
import Link from "next/link";
import Navbar from "../components/Navbar";

let minimalisticLPGitHubLink =
  "https://github.com/fabianszyman/onMyWayToCoding/tree/main/html-css-tutorials/minimalistic-website";

export default function Home() {
  let pageName = "Minimalistic landing page";
  return (
    <div>
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotifyIcon.ico" />
      </Head>
      <main className="text-white font-gothamBold bg-black h-screen break-words md:px-24 lg:px-40 2xl:px-48 ">
        <Navbar headerName={pageName} />
        <div className=" bg-black px-4 grid grid-cols-1 lg:grid-cols-8 gap-6 py-20">
          <div id="leftContainer" className="lg:col-span-4 bg-black">
            <div id="headerContainer" className=" lg:hidden">
              <h1 className=" font-gothamLight text-sm">Personal Project</h1>
              <h2 className=" text-2xl ">{pageName}</h2>
            </div>

            <div
              id="imageContainer"
              className="pt-2 lg:pt-12 w-auto rounded lg:hidden overflow-hidden"
            >
              <div className="relative">
                <Image
                  src={minimalisticLPBigImage}
                  alt="fallback-text"
                  className="rounded"
                />
                <a
                  href={minimalisticLPGitHubLink}
                  target="_blank"
                  rel="noreferrer"
                >
                  <button className=" absolute top-4 right-4 text-black bg-white rounded-full px-7 py-3 hover:scale-105 border border-gray-400 hover:border-green-500  m-2 ">
                    <div className="flex items-center gap-2">
                      <BsGithub />
                      Github
                    </div>
                  </button>
                </a>
              </div>
            </div>

            <div id="headerContainer" className="hidden lg:inline-block pb-3">
              <h1 className=" font-gothamLight text-sm">Personal Project</h1>
              <h2 className=" text-2xl ">{pageName}</h2>
            </div>
            <div id="textContainer" className="pt-4">
              <div className="text-lg">What?</div>
              <div className="font-gothamLight text-lg pt-1">
                <p className="pb-2">
                  This page is a very basic Landing Page for a Yoga Studio,
                  which uses basic HTML, CSS and Javascript.
                </p>
              </div>
              <div className="text-lg pt-6">Why?</div>
              <div className="font-gothamLight text-lg pt-1">
                <ul>
                  <li>
                    1. Trying to catch update my HTML, CSS by creating a
                    responsive design.
                  </li>
                  <li>
                    2. Trying to improve my Javascript knowledge by implementing{" "}
                    <a
                      href="https://greensock.com/get-started/"
                      className="underline hover:underline hover:text-green-500"
                    >
                      gsap{" "}
                    </a>
                    animation.
                  </li>
                </ul>
              </div>
              <div className="text-lg pt-6">How?</div>
              <div className="font-gothamLight text-lg pt-1">
                <ul>
                  <li>1. Create basic Elements in basic HTML</li>
                  <li>2. Formatting layout with CSS</li>
                  <li>
                    3. Adding script.js file and addEventListener function using{" "}
                    <a
                      href="https://greensock.com/get-started/"
                      className="underline hover:underline hover:text-green-500"
                    >
                      gsap
                    </a>{" "}
                    for slide in animation for burger menu click action.
                  </li>
                  <li>4. Add further sections incl. videos</li>
                  <li>
                    5. Add function that starts video play, when user scrolls
                    down and video element is inside her view section.
                  </li>
                </ul>
              </div>
              <div className="text-lg pt-6">Github-Link:</div>
              <div className="font-gothamLight text-lg pt-1 pb-20">
                <a
                  href={minimalisticLPGitHubLink}
                  className="underline hover:underline hover:text-green-500"
                >
                  {minimalisticLPGitHubLink}
                </a>
              </div>
            </div>
          </div>

          <div
            id="rightContainer"
            className="lg:col-span-4 lg:py-4 bg-black hidden lg:inline-block"
          >
            <div
              id="imageContainer"
              className="pt-2 lg:pt-12 h-1/3 w-auto rounded "
            >
              <div className="relative">
                <Image
                  src={minimalisticLPSmallImage}
                  alt="fallback-text"
                  className="overflow-hidden rounded"
                />
                <a
                  href="https://github.com/fabianszyman/onMyWayToCoding/tree/main/html-css-tutorials/minimalistic-website"
                  target="_blank"
                  rel="noreferrer"
                >
                  <button className=" absolute top-4 right-4 text-black bg-white rounded-full px-7 py-3 hover:scale-105 border border-gray-400 hover:border-green-500  m-2 ">
                    <div className="flex items-center gap-2">
                      <BsGithub />
                      Github
                    </div>
                  </button>
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
