import Head from "next/head";
import Image from "next/image";
import profileImage from "../public/profileImage.jpg";
import reaectToDoAppImage from "../public/reactToDoAppImage.png";
import minimalisticLandingPageImage from "../public/minimalisticLandingPage.png";
import check24ProfisLogo from "../public/check24ProfisLogo.png";
import printManiaLogo from "../public/print_mania.png";
import instaBotLogo from "../public/instabot.jpeg";
import btuLogoImage from "../public/btuLogo.png";
import ibmIxLogo from "../public/ibmIx.png";
import auto1Logo from "../public/auto1GroupLogo.jpeg";
import bvLogo from "../public/bvLogo.jpeg";
import { MdVerified } from "react-icons/md";
import { AiFillPlayCircle } from "react-icons/ai";
import { BsThreeDots, BsFillPlayFill } from "react-icons/bs";
import { IoIosArrowBack } from "react-icons/io";
import Link from "next/link";
import Navbar from "../components/Navbar";

export default function Home() {
  let pageName = "Portfolio Page";
  return (
    <div>
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotifyIcon.ico" />
      </Head>
      <main className="text-white font-gothamBold bg-black h-screen ">
        <Navbar headerName={pageName} />
        <div className=" bg-black pt-16 px-4">
          <h2>Personal Projects</h2>
          {/*SECTION: To Do App*/}
          <div class="group">
            <div className="w-full font-gothamLight text-xs">
              <Link href="/minimalisticLandingPage">
                <div className="flex items-center gap-1 text-gray-400 py-2 group-hover:bg-gray-700 rounded-md max-w-xl relative ">
                  <div className="w-1/12 h-12 py-4 px-4">1</div>
                  <div className="w-12 h-12">
                    <Image
                      src={minimalisticLandingPageImage}
                      alt="fallback-text"
                      className="w-12 h-12"
                      layout="fill"
                      objectfit="cover"
                    />
                  </div>
                  <div className="w-6/12 py-4 px-3 text-left group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    Minimalistic Landing Page
                  </div>
                  <div className=" w-2/12 h-12 py-4 text-right group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    HTML|CSS
                  </div>
                  <div className="w-2/12 h-12 py-4 px-2 text-right text-ellipsis whitespace-nowrap overflow-hidden">
                    12 hours
                  </div>
                </div>
              </Link>
            </div>
          </div>
        </div>

        <div className=" bg-black px-4">
          {/*SECTION: Minimalistic Landing Page*/}
          <div class="group">
            <div className="w-full font-gothamLight text-xs">
              <Link href="/toDoApp">
                <div className="flex items-center gap-1 text-gray-400 py-2 group-hover:bg-gray-700 rounded-md max-w-xl relative ">
                  <div className="w-1/12 h-12 py-4 px-4">2</div>
                  <div className="w-12 h-12">
                    <Image
                      src={reaectToDoAppImage}
                      alt="fallback-text"
                      className="w-12 h-12"
                      layout="fill"
                      objectfit="cover"
                    />
                  </div>
                  <div className="w-6/12 py-4 px-3 text-left group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    To Do App
                  </div>
                  <div className=" w-2/12 h-12 py-4 text-right group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    React
                  </div>
                  <div className="w-2/12 h-12 py-4 px-2 text-right text-ellipsis whitespace-nowrap overflow-hidden">
                    23 hours
                  </div>
                </div>
              </Link>
            </div>
          </div>

          {/*SECTION: Instagram AutoLike Bot*/}
          <div class="group">
            <div className="w-full font-gothamLight text-xs">
              <Link href="/instagramLikeBot">
                <div className="flex items-center gap-1 text-gray-400 py-2 group-hover:bg-gray-700 rounded-md max-w-xl relative ">
                  <div className="w-1/12 h-12 py-4 px-4">3</div>
                  <div className="w-12 h-12">
                    <Image
                      src={instaBotLogo}
                      alt="fallback-text"
                      className="w-12 h-12"
                      layout="fill"
                      objectfit="cover"
                    />
                  </div>
                  <div className="w-5/12 py-4 px-3 text-left group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    Instagram LikeBot
                  </div>
                  <div className=" w-3/12 h-12 py-4 text-right group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    Node.js|JavaScript
                  </div>
                  <div className="w-2/12 h-12 py-4 px-2 text-right text-ellipsis whitespace-nowrap overflow-hidden">
                    34 hours
                  </div>
                </div>
              </Link>
            </div>
          </div>
        </div>

        <div id="employmentHistorySection" className="bg-black">
          <h2 className="text-3xls p-4 text-white">Work related Projects</h2>
          <div id="myPortfolioItems" className=" font-gothamBold text-xs">
            <div id="PortfolioItemGroup" class="group">
              <Link href="/forkProject">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white">
                        <h4 className="text-ellipsis w-18 whitespace-nowrap overflow-hidden inline-block text-base">
                          Fork Project
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Senior PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      January 2022 - Present
                    </p>
                  </div>
                </div>
              </Link>
            </div>

            <div id="PortfolioItemGroup" class="group">
              <Link href="/backofficeProject">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white w-18">
                        <h4 className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base">
                          Backoffice Project
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Senior PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      April 2019 - December 2021
                    </p>
                  </div>
                </div>
              </Link>
            </div>

            <div id="PortfolioItemGroup" class="group">
              <Link href="/nativeMessenger">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white w-18">
                        <h4 className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base">
                          Native Messenger (iOS & Android)
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Senior PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      March 2019 - Present
                    </p>
                  </div>
                </div>
              </Link>
            </div>

            <div id="PortfolioItemGroup" class="group">
              <Link href="/eggCrackerProject">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white">
                        <h4 className="text-ellipsis w-18 whitespace-nowrap overflow-hidden inline-block text-base">
                          Egg Cracker
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Professional PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      January 2022 - Present
                    </p>
                  </div>
                </div>
              </Link>
            </div>

            <div id="PortfolioItemGroup" class="group">
              <Link href="/documentUploaderProject">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white w-18">
                        <h4 className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base">
                          Document Uploader
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Professional PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      April 2019 - December 2021
                    </p>
                  </div>
                </div>
              </Link>
            </div>

            <div id="PortfolioItemGroup" class="group">
              <Link href="/invoiceProject">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white w-18">
                        <h4 className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base">
                          Invoice Feature
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Professional PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      March 2019 - Present
                    </p>
                  </div>
                </div>
              </Link>
            </div>

            <div id="PortfolioItemGroup" class="group">
              <Link href="/happinessGarantieProject">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white w-18">
                        <h4 className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base">
                          Happiness Garantie
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Professional PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      March 2019 - Present
                    </p>
                  </div>
                </div>
              </Link>
            </div>

            <div id="PortfolioItemGroup" class="group">
              <Link href="/questionEditor">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white">
                        <h4 className="text-ellipsis w-18 whitespace-nowrap overflow-hidden inline-block text-base">
                          Question Editor
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Junior PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      January 2022 - Present
                    </p>
                  </div>
                </div>
              </Link>
            </div>

            <div id="PortfolioItemGroup" class="group">
              <Link href="/instantResultPage">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white w-18">
                        <h4 className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base">
                          Instant Result Page
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Junior PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      April 2019 - December 2021
                    </p>
                  </div>
                </div>
              </Link>
            </div>

            <div id="PortfolioItemGroup" class="group">
              <Link href="/paymentProcessProject">
                <div
                  id="PortfolioItem"
                  className="py-2 mx-4 group-hover:bg-gray-700 rounded-md max-w-xl"
                >
                  <div
                    id="containerAllItems"
                    className="flex items-center justify-between gap-6"
                  >
                    <div
                      id="containerImageTitle"
                      className="flex items-center gap-6"
                    >
                      <div className="ml-2 w-16 h-16">
                        <Image
                          src={check24ProfisLogo}
                          alt="fallback-text"
                          layout="fill"
                          objectfit="cover"
                        />
                      </div>
                      <div className="text-white w-18">
                        <h4 className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-base">
                          Payment process (Stripe)
                        </h4>
                        <p className="group-hover:text-white text-left font-gothamLight">
                          CHECK24 Profis (Junior PM)
                        </p>
                      </div>
                    </div>
                    <p className="text-ellipsis whitespace-nowrap overflow-hidden inline-block text-right max-w-xs mr-2">
                      March 2019 - Present
                    </p>
                  </div>
                </div>
              </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
