import Head from "next/head";
import Image from "next/image";
import profileImage from "../public/profileImage.jpg";
import reaectToDoAppImage from "../public/reactToDoAppImage.png";
import minimalisticLandingPageImage from "../public/minimalisticLandingPage.png";
import check24ProfisLogo from "../public/check24ProfisLogo.png";
import printManiaLogo from "../public/print_mania.png";
import instaBotLogo from "../public/instabot.jpeg";
import btuLogoImage from "../public/btuLogo.png";
import ibmIxLogo from "../public/ibmIx.png";
import auto1Logo from "../public/auto1GroupLogo.jpeg";
import bvLogo from "../public/bvLogo.jpeg";
import { MdVerified } from "react-icons/md";
import { AiFillPlayCircle } from "react-icons/ai";
import { BsThreeDots, BsFillPlayFill } from "react-icons/bs";
import { IoIosArrowBack } from "react-icons/io";
import Link from "next/link";
import Navbar from "../components/Navbar";
import BigListItem from "../components/BigListItem";

let growSignUpsRatesProjectPage = "/growSignUpsRatesProject";
let documentUploaderProjectPage = "/documentUploaderProject";
let invoiceProjectPage = "/invoiceProject";
let forkProjectPage = "/forkProject";
let backofficeProjectPage = "/backofficeProject";
let nativeMessengerProjectPage = "/nativeMessenger";
let eggCrackerProjectPage = "/eggCrackerProject";
let questionEditorPage = "/questionEditor";
let instantResultPage = "/instantResultPage";
let paymentProcessProjectPage = "/paymentProcessProject";
let happinessGarantieProjectPage = "/happinessGarantieProject";

export default function Home() {
  let pageName = "Portfolio";
  return (
    <div>
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotifyIcon.ico" />
      </Head>
      <main className="text-white font-gothamBold h-screen md:px-24 lg:px-48 3xl:px-128 bg-black  ">
        <Navbar headerName={pageName} />
        <div className=" bg-black pt-20 px-4">
          <h2 className="pb-4">Personal projects</h2>
          {/*SECTION: To Do App*/}
          <div class="group">
            <div className="w-full font-gothamLight text-xs">
              <Link href="/minimalisticLandingPage">
                <div className="flex items-center gap-1 text-gray-400 py-2 group-hover:bg-gray-700 rounded-md max-w-xl relative ">
                  <div className="w-1/12 h-12 py-4 px-4">1</div>
                  <div className="w-12 h-12">
                    <Image
                      src={minimalisticLandingPageImage}
                      alt="fallback-text"
                      className="w-12 h-12"
                      layout="fill"
                      objectfit="cover"
                    />
                  </div>
                  <div className="w-6/12 py-4 px-3 text-left group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    Minimalistic landing page - TBD
                  </div>
                  <div className=" w-2/12 h-12 py-4 text-right group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    HTML|CSS
                  </div>
                  <div className="w-2/12 h-12 py-4 px-2 text-right text-ellipsis whitespace-nowrap overflow-hidden">
                    12 hours
                  </div>
                </div>
              </Link>
            </div>
          </div>
        </div>

        <div className=" bg-black px-4">
          {/*SECTION: Minimalistic Landing Page*/}
          <div class="group">
            <div className="w-full font-gothamLight text-xs">
              <Link href="/toDoApp">
                <div className="flex items-center gap-1 text-gray-400 py-2 group-hover:bg-gray-700 rounded-md max-w-xl relative ">
                  <div className="w-1/12 h-12 py-4 px-4">2</div>
                  <div className="w-12 h-12">
                    <Image
                      src={reaectToDoAppImage}
                      alt="fallback-text"
                      className="w-12 h-12"
                      layout="fill"
                      objectfit="cover"
                    />
                  </div>
                  <div className="w-6/12 py-4 px-3 text-left group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    To do app - TBD englisch
                  </div>
                  <div className=" w-2/12 h-12 py-4 text-right group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    React
                  </div>
                  <div className="w-2/12 h-12 py-4 px-2 text-right text-ellipsis whitespace-nowrap overflow-hidden">
                    23 hours
                  </div>
                </div>
              </Link>
            </div>
          </div>

          {/*SECTION: Instagram AutoLike Bot*/}
          <div class="group">
            <div className="w-full font-gothamLight text-xs">
              <Link href="/instagramLikeBot">
                <div className="flex items-center gap-1 text-gray-400 py-2 group-hover:bg-gray-700 rounded-md max-w-xl relative ">
                  <div className="w-1/12 h-12 py-4 px-4">3</div>
                  <div className="w-12 h-12">
                    <Image
                      src={instaBotLogo}
                      alt="fallback-text"
                      className="w-12 h-12"
                      layout="fill"
                      objectfit="cover"
                    />
                  </div>
                  <div className="w-5/12 py-4 px-3 text-left group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    Instagram LikeBot - TBD englisch
                  </div>
                  <div className=" w-3/12 h-12 py-4 text-right group-hover:text-white text-ellipsis whitespace-nowrap overflow-hidden">
                    Node.js|JavaScript
                  </div>
                  <div className="w-2/12 h-12 py-4 px-2 text-right text-ellipsis whitespace-nowrap overflow-hidden">
                    34 hours
                  </div>
                </div>
              </Link>
            </div>
          </div>
        </div>

        <div id="employmentHistorySection" className="bg-black">
          <h2 className="text-3xls p-4 text-white">Work related projects</h2>
          <div id="myPortfolioItems" className=" font-gothamBold text-xs">
            <BigListItem
              src={check24ProfisLogo}
              title="Native messengers (iOS & Android) - DONE"
              subline="CHECK24 Profis"
              durationText="2022"
              href={nativeMessengerProjectPage}
            />

            <BigListItem
              src={check24ProfisLogo}
              title="Fork project - DONE"
              subline="CHECK24 Profis"
              durationText="2021 - 2022"
              href={forkProjectPage}
            />

            <BigListItem
              src={check24ProfisLogo}
              title="Backoffice project - DONE"
              subline="CHECK24 Profis"
              durationText="2021"
              href={backofficeProjectPage}
            />

            <BigListItem
              src={check24ProfisLogo}
              title="Grow sign ups rates - DONE"
              subline="CHECK24 Profis"
              durationText="2020"
              href={growSignUpsRatesProjectPage}
            />

            <BigListItem
              src={check24ProfisLogo}
              title="Question editor - DONE"
              subline="CHECK24 Profis"
              durationText="2019"
              href={questionEditorPage}
            />

            <BigListItem
              src={check24ProfisLogo}
              title="Payment process (Stripe) - TBD"
              subline="CHECK24 Profis"
              durationText="2018 - 2019"
              href={paymentProcessProjectPage}
            />
          </div>
        </div>
      </main>
    </div>
  );
}
