import Head from 'next/head';
import Image from 'next/image';
import profileImage from '../public/profileImage.jpg';
import reaectToDoAppImage from '../public/reactToDoAppImage.png'
import minimalisticLandingPageImage from '../public/minimalisticLandingPage.png'
import check24ProfisLogo from '../public/check24ProfisLogo.png'
import printManiaLogo from '../public/print_mania.png'
import instaBotLogo from '../public/instabot.jpeg'
import btuLogoImage from '../public/btuLogo.png'
import ibmIxLogo from '../public/ibmIx.png'
import auto1Logo from '../public/auto1GroupLogo.jpeg'
import bvLogo from '../public/bvLogo.jpeg'
import {MdVerified} from 'react-icons/md';
import {AiFillPlayCircle} from 'react-icons/ai';
import {BsThreeDots, BsFillPlayFill} from 'react-icons/bs'
import {IoIosArrowBack} from 'react-icons/io'
import Link from 'next/link';
import Navbar from '../components/Navbar';
import BigListItem from '../components/BigListItem'

let forkProjectPage = '/forkProject';
let backofficeProjectPage = '/backofficeProject';
let nativeMessengerProjectPage = '/nativeMessenger';


export default function Home() {
    let pageName ='Work related projects (Senior PM)'
  return (
    <div >
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/spotifyIcon.ico" />
      </Head>
      <main className='text-white font-gothamBold bg-black h-screen '>
      <Navbar headerName={pageName}/>
            {/*SECTION: Employment History*/}
            <div className='w-screen pt-14'>
                <div id='employmentHistorySection' className='bg-black'>
                    <h2 className="text-3xls p-4 text-white">Senior Product Manager (CHECK24 Profis)</h2>
                    <div id="myPortfolioItems" className=' font-gothamBold text-xs'>

                    <BigListItem 
                    src={check24ProfisLogo}
                    title='Fork Project'
                    subline='CHECK24 Profis'
                    durationText='January 2022 - Present'
                    href={forkProjectPage}
                    />  

                    <BigListItem 
                    src={check24ProfisLogo}
                    title='Backoffice Project'
                    subline='CHECK24 Profis'
                    durationText='April 2019 - December 2021'
                    href={backofficeProjectPage}
                    />  

                    <BigListItem 
                    src={check24ProfisLogo}
                    title='Native Messengers (iOS & Android)'
                    subline='CHECK24 Profis'
                    durationText='March 2019 - Present'
                    href={nativeMessengerProjectPage}
                    />  
                        


                    </div>

                </div>
            </div>
      </main>
    </div>
  )
}


